trigger:
- dev
- master

pr:
- master


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/GdprInfo.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nugetPackOutputDir: '$(Build.ArtifactStagingDirectory)/nuget/'



steps:
- task: MSBuild@1
  displayName: Build Solution
  inputs:
    solution: '**/src/GdprInfo.csproj'
    configuration: $(buildConfiguration)
    platform: $(buildPlatform)
    msbuildArguments: '/restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false'

# - task: MSBuild@1
#   #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#   displayName: Pack NuGets
#   inputs:
#     solution: '**/src/GdprInfo.csproj'
#     configuration: $(buildConfiguration)
#     platform: $(buildPlatform)
#     msbuildArguments: '/t:Pack /p:PackageVersion=$(major).$(minor).$(patch) /p:PackageOutputPath="$(nugetPackOutputDir)"'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/src/GdprInfo.csproj'
    packDestination: '$(nugetPackOutputDir)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: '$(major).$(minor).$(patch)'
    includeSymbols: true

- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: 'test'
    publishTestResults: true
    projects: '**/tests/GdprInfo.Tests/GdprInfo.Tests.csproj'
    testRunTitle: 'Shared Layer Tests'
    workingDirectory: '$(System.DefaultWorkingDirectory)'



- task: PublishBuildArtifacts@1
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(nugetPackOutputDir)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'