# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- dev
- master

pr:
- master


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/GdprInfo.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nugetPackOutputDir: '$(Build.ArtifactStagingDirectory)/nuget'



steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: 'test'
    projects: '**/tests/GdprInfo.Tests/GdprInfo.Tests.csproj'
    testRunTitle: 'Shared Layer Tests'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Shared Layer Tests'
    buildPlatform: '$(buildPlatform)'
    buildConfiguration: '$(buildConfiguration)'

- task: MSBuild@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Pack NuGets
  inputs:
    solution: '**/src/GdprInfo.csproj'
    configuration: $(buildConfiguration)
    msbuildArguments: '/t:Pack /p:PackageVersion=$(major).$(minor).$(patch) /p:PackageOutputPath="$(nugetPackOutputDir)"'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(nugetPackOutputDir)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'