# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- dev
- master

pr:
- master


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/GdprInfo.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  nugetPackOutputDir: '$(Build.ArtifactStagingDirectory)/Packages'



steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/tests/GdprInfo.Tests/GdprInfo.Tests.csproj'
    testRunTitle: 'Shared Layer Tests'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'pack'
    packagesToPack: '**/src/GdprInfo.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: '$(major).$(minor).$(patch)'
    outputDir: '$(nugetPackOutputDir)'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(nugetPackOutputDir)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'